# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d043e4c4b319ec7d19fdae8319ae7fd603e0fe9010f14c81a00aaa2c46b5bca63954151e97bd9bfc572109df4a998a09917c619e6297bec7b17dbc2f284268

test:
  secret_key_base: a97e6ceb281a3e520fb2661ec94392aa2266c021e27b3a1428b004a6d5edb96dd759ef92fc6d7e1eb32328742c446e79bfe9b51d2e49c5ed4edc9becb343b747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
